# compose file for local development
# UI on http://127.0.0.1:8080/
#
# build: docker compose -f docker-dev-compose.yml build
# start: docker compose -f docker-dev-compose.yml up
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SKIP_FRONTEND_TEST: "true"
    
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

    ports:
      - "8080:8080" # primary rest server

    environment:
      - TIME_ZONE=Europe/Moscow
      - TEST_MODE=true
      - ADDRESS=0.0.0.0
      - STORE_TYPE=sqlite
      - STORE_SQLITE_SOURCE=./bin/app.db

    volumes:
      - ./var:/srv/var
      - ./backend/bin:/srv/bin
