[env]
CGO_ENABLED = "0"

[tools]
air = "latest"
go = "latest"
golangci-lint = "latest"

[tasks.seed]
description = "Seed database"
run = """
rm -f ./bin/app.db*
go run ./app dev seed --store.db ./bin/app.db
"""

[tasks.token]
description = "Generate token for user"
run = """
go run ./app dev token --store.db ./bin/app.db
"""

[tasks.checks]
description = "Run checks"
sources = [
    "./**/*.go",
]
usage = '''
flag "--fix" {
    help "Enable automatic fixes"
}
'''
quiet = true
run = '''
golangci-lint run --config .golangci.yml --show-stats=false ./... ${usage_fix:+--fix}
'''

[tasks.tests]
description = "Run tests, silent unless something fails"
quiet = true
run = '''
if ! output=$(go test ./... 2>&1); then
    printf '%s\n' "$output"
    exit 1
fi
'''

[tasks.coverage]
description = "Run coverage"
run = "go test -cover -coverprofile=profile.cov ./... && go tool cover -func=profile.cov"
