### login
# @name login

POST http://localhost:8000/api/v1/auth/login HTTP/1.1

{
  "email": "new_user@example.com"
}


### Confirm login

POST http://localhost:8000/api/v1/auth/login/confirm HTTP/1.1

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJOZXNrdWNoa2EiLCJleHAiOjE3NjU4MTcyODYsImp0aSI6ImNiZjBjMDdlMmVjOWFhMzdkMTdkMTk3MTIzNGMwMTNhZjUxMmFlMzgiLCJkYXRhIjp7ImVtYWlsIjoibmV3X3VzZXJAZXhhbXBsZS5jb20ifX0.rD9niMH0IMqBwzF5PgUZLIGy8bv5RKrnvVHEcXiv61s"
}

### Logout

POST http://localhost:8000/api/v1/auth/logout HTTP/1.1

### Get user

GET http://localhost:8000/api/v1/auth/user HTTP/1.1