### login
# @name login

POST http://localhost:8000/api/v1/auth/login HTTP/1.1

{
  "email": "new_user@example.com"
}


### Confirm login

POST http://localhost:8000/api/v1/auth/login/confirm HTTP/1.1

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJOZXNrdWNoa2EiLCJleHAiOjE3NjY1ODc1MDEsImp0aSI6ImZlZjM0OGQ2NDJhZWE4MDY1NWM4MTczZTdhMjg5OGVhNTAzM2Y0M2MiLCJkYXRhIjp7ImVtYWlsIjoic29tZUBzb21lLmNvbSJ9fQ.-jb5GLYuIIDRF2fLBytjuTydJxSgaLOVotRy-pRiefA"
}

### Logout

POST http://localhost:8000/api/v1/auth/logout HTTP/1.1

### Get user

GET http://localhost:8000/api/v1/auth/user HTTP/1.1