/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutsIndexRouteImport } from './routes/workouts.index'
import { Route as WorkoutsNewRouteImport } from './routes/workouts.new'
import { Route as WorkoutsWorkoutIdRouteImport } from './routes/workouts.$workoutId'
import { Route as WorkoutsWorkoutIdEditRouteImport } from './routes/workouts.$workoutId_.edit'

const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsIndexRoute = WorkoutsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkoutsRoute,
} as any)
const WorkoutsNewRoute = WorkoutsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WorkoutsRoute,
} as any)
const WorkoutsWorkoutIdRoute = WorkoutsWorkoutIdRouteImport.update({
  id: '/$workoutId',
  path: '/$workoutId',
  getParentRoute: () => WorkoutsRoute,
} as any)
const WorkoutsWorkoutIdEditRoute = WorkoutsWorkoutIdEditRouteImport.update({
  id: '/$workoutId_/edit',
  path: '/$workoutId/edit',
  getParentRoute: () => WorkoutsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/welcome': typeof WelcomeRoute
  '/workouts': typeof WorkoutsRouteWithChildren
  '/workouts/$workoutId': typeof WorkoutsWorkoutIdRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/workouts/': typeof WorkoutsIndexRoute
  '/workouts/$workoutId/edit': typeof WorkoutsWorkoutIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/welcome': typeof WelcomeRoute
  '/workouts/$workoutId': typeof WorkoutsWorkoutIdRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/workouts': typeof WorkoutsIndexRoute
  '/workouts/$workoutId/edit': typeof WorkoutsWorkoutIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/welcome': typeof WelcomeRoute
  '/workouts': typeof WorkoutsRouteWithChildren
  '/workouts/$workoutId': typeof WorkoutsWorkoutIdRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/workouts/': typeof WorkoutsIndexRoute
  '/workouts/$workoutId_/edit': typeof WorkoutsWorkoutIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/welcome'
    | '/workouts'
    | '/workouts/$workoutId'
    | '/workouts/new'
    | '/workouts/'
    | '/workouts/$workoutId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/welcome'
    | '/workouts/$workoutId'
    | '/workouts/new'
    | '/workouts'
    | '/workouts/$workoutId/edit'
  id:
    | '__root__'
    | '/'
    | '/welcome'
    | '/workouts'
    | '/workouts/$workoutId'
    | '/workouts/new'
    | '/workouts/'
    | '/workouts/$workoutId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WelcomeRoute: typeof WelcomeRoute
  WorkoutsRoute: typeof WorkoutsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/': {
      id: '/workouts/'
      path: '/'
      fullPath: '/workouts/'
      preLoaderRoute: typeof WorkoutsIndexRouteImport
      parentRoute: typeof WorkoutsRoute
    }
    '/workouts/new': {
      id: '/workouts/new'
      path: '/new'
      fullPath: '/workouts/new'
      preLoaderRoute: typeof WorkoutsNewRouteImport
      parentRoute: typeof WorkoutsRoute
    }
    '/workouts/$workoutId': {
      id: '/workouts/$workoutId'
      path: '/$workoutId'
      fullPath: '/workouts/$workoutId'
      preLoaderRoute: typeof WorkoutsWorkoutIdRouteImport
      parentRoute: typeof WorkoutsRoute
    }
    '/workouts/$workoutId_/edit': {
      id: '/workouts/$workoutId_/edit'
      path: '/$workoutId/edit'
      fullPath: '/workouts/$workoutId/edit'
      preLoaderRoute: typeof WorkoutsWorkoutIdEditRouteImport
      parentRoute: typeof WorkoutsRoute
    }
  }
}

interface WorkoutsRouteChildren {
  WorkoutsWorkoutIdRoute: typeof WorkoutsWorkoutIdRoute
  WorkoutsNewRoute: typeof WorkoutsNewRoute
  WorkoutsIndexRoute: typeof WorkoutsIndexRoute
  WorkoutsWorkoutIdEditRoute: typeof WorkoutsWorkoutIdEditRoute
}

const WorkoutsRouteChildren: WorkoutsRouteChildren = {
  WorkoutsWorkoutIdRoute: WorkoutsWorkoutIdRoute,
  WorkoutsNewRoute: WorkoutsNewRoute,
  WorkoutsIndexRoute: WorkoutsIndexRoute,
  WorkoutsWorkoutIdEditRoute: WorkoutsWorkoutIdEditRoute,
}

const WorkoutsRouteWithChildren = WorkoutsRoute._addFileChildren(
  WorkoutsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WelcomeRoute: WelcomeRoute,
  WorkoutsRoute: WorkoutsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
