/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as LoginConfirmRouteImport } from './routes/login.confirm'
import { Route as WorkoutsIndexRouteImport } from './routes/workouts.index'
import { Route as WorkoutsWorkoutIdRouteImport } from './routes/workouts.$workoutId'
import { Route as WorkoutsManageRouteImport } from './routes/workouts.manage'
import { Route as WorkoutsNewRouteImport } from './routes/workouts.new'
import { Route as WorkoutsWorkoutIdEditRouteImport } from './routes/workouts.$workoutId_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRoute,
} as any)
const LoginConfirmRoute = LoginConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => LoginRoute,
} as any)
const WorkoutsIndexRoute = WorkoutsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkoutsRoute,
} as any)
const WorkoutsWorkoutIdRoute = WorkoutsWorkoutIdRouteImport.update({
  id: '/$workoutId',
  path: '/$workoutId',
  getParentRoute: () => WorkoutsRoute,
} as any)
const WorkoutsManageRoute = WorkoutsManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => WorkoutsRoute,
} as any)
const WorkoutsNewRoute = WorkoutsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WorkoutsRoute,
} as any)
const WorkoutsWorkoutIdEditRoute = WorkoutsWorkoutIdEditRouteImport.update({
  id: '/$workoutId_/edit',
  path: '/$workoutId/edit',
  getParentRoute: () => WorkoutsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/workouts': typeof WorkoutsRouteWithChildren
  '/login/confirm': typeof LoginConfirmRoute
  '/workouts/$workoutId': typeof WorkoutsWorkoutIdRoute
  '/workouts/manage': typeof WorkoutsManageRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/login/': typeof LoginIndexRoute
  '/workouts/': typeof WorkoutsIndexRoute
  '/workouts/$workoutId/edit': typeof WorkoutsWorkoutIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/login/confirm': typeof LoginConfirmRoute
  '/workouts/$workoutId': typeof WorkoutsWorkoutIdRoute
  '/workouts/manage': typeof WorkoutsManageRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/login': typeof LoginIndexRoute
  '/workouts': typeof WorkoutsIndexRoute
  '/workouts/$workoutId/edit': typeof WorkoutsWorkoutIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/settings': typeof SettingsRoute
  '/welcome': typeof WelcomeRoute
  '/workouts': typeof WorkoutsRouteWithChildren
  '/login/confirm': typeof LoginConfirmRoute
  '/workouts/$workoutId': typeof WorkoutsWorkoutIdRoute
  '/workouts/manage': typeof WorkoutsManageRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/login/': typeof LoginIndexRoute
  '/workouts/': typeof WorkoutsIndexRoute
  '/workouts/$workoutId_/edit': typeof WorkoutsWorkoutIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/welcome'
    | '/workouts'
    | '/login/confirm'
    | '/workouts/$workoutId'
    | '/workouts/manage'
    | '/workouts/new'
    | '/login/'
    | '/workouts/'
    | '/workouts/$workoutId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/welcome'
    | '/login/confirm'
    | '/workouts/$workoutId'
    | '/workouts/manage'
    | '/workouts/new'
    | '/login'
    | '/workouts'
    | '/workouts/$workoutId/edit'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings'
    | '/welcome'
    | '/workouts'
    | '/login/confirm'
    | '/workouts/$workoutId'
    | '/workouts/manage'
    | '/workouts/new'
    | '/login/'
    | '/workouts/'
    | '/workouts/$workoutId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  WelcomeRoute: typeof WelcomeRoute
  WorkoutsRoute: typeof WorkoutsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/confirm': {
      id: '/login/confirm'
      path: '/confirm'
      fullPath: '/login/confirm'
      preLoaderRoute: typeof LoginConfirmRouteImport
      parentRoute: typeof LoginRoute
    }
    '/workouts/': {
      id: '/workouts/'
      path: '/'
      fullPath: '/workouts/'
      preLoaderRoute: typeof WorkoutsIndexRouteImport
      parentRoute: typeof WorkoutsRoute
    }
    '/workouts/$workoutId': {
      id: '/workouts/$workoutId'
      path: '/$workoutId'
      fullPath: '/workouts/$workoutId'
      preLoaderRoute: typeof WorkoutsWorkoutIdRouteImport
      parentRoute: typeof WorkoutsRoute
    }
    '/workouts/manage': {
      id: '/workouts/manage'
      path: '/manage'
      fullPath: '/workouts/manage'
      preLoaderRoute: typeof WorkoutsManageRouteImport
      parentRoute: typeof WorkoutsRoute
    }
    '/workouts/new': {
      id: '/workouts/new'
      path: '/new'
      fullPath: '/workouts/new'
      preLoaderRoute: typeof WorkoutsNewRouteImport
      parentRoute: typeof WorkoutsRoute
    }
    '/workouts/$workoutId_/edit': {
      id: '/workouts/$workoutId_/edit'
      path: '/$workoutId/edit'
      fullPath: '/workouts/$workoutId/edit'
      preLoaderRoute: typeof WorkoutsWorkoutIdEditRouteImport
      parentRoute: typeof WorkoutsRoute
    }
  }
}

interface LoginRouteChildren {
  LoginConfirmRoute: typeof LoginConfirmRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginConfirmRoute: LoginConfirmRoute,
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface WorkoutsRouteChildren {
  WorkoutsWorkoutIdRoute: typeof WorkoutsWorkoutIdRoute
  WorkoutsManageRoute: typeof WorkoutsManageRoute
  WorkoutsNewRoute: typeof WorkoutsNewRoute
  WorkoutsIndexRoute: typeof WorkoutsIndexRoute
  WorkoutsWorkoutIdEditRoute: typeof WorkoutsWorkoutIdEditRoute
}

const WorkoutsRouteChildren: WorkoutsRouteChildren = {
  WorkoutsWorkoutIdRoute: WorkoutsWorkoutIdRoute,
  WorkoutsManageRoute: WorkoutsManageRoute,
  WorkoutsNewRoute: WorkoutsNewRoute,
  WorkoutsIndexRoute: WorkoutsIndexRoute,
  WorkoutsWorkoutIdEditRoute: WorkoutsWorkoutIdEditRoute,
}

const WorkoutsRouteWithChildren = WorkoutsRoute._addFileChildren(
  WorkoutsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRouteWithChildren,
  SettingsRoute: SettingsRoute,
  WelcomeRoute: WelcomeRoute,
  WorkoutsRoute: WorkoutsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
