name: Building app

on:
  push:
    branches: [main]
    tags: [v*]
    paths:
      - ".github/workflows/build.yml"
      - "backend/**"
      - "frontend/**"
      - ".dockerignore"
      - "Dockerfile"
      - "!**.md"
  pull_request:
    paths:
      - ".github/workflows/build.yml"
      - "backend/**"
      - "frontend/**"
      - ".dockerignore"
      - "Dockerfile"
      - "!**.md"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Yandex Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: build docker image without pushing (only outside master)
        if: ${{ github.ref != 'refs/heads/main' }}
        run: |
          docker buildx build \
            --build-arg SKIP_BACKEND_TEST=true --build-arg SKIP_FRONTEND_TEST=true \
            --platform linux/amd64 .

      - name: build and deploy master image to Yandex Container Registry
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          CR_REGISTRY: crpl78lea8jvcc10cnu3
          CR_REPOSITORY: neskuchka
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker buildx build --push \
            --build-arg SKIP_BACKEND_TEST=true --build-arg SKIP_FRONTEND_TEST=true \
            --platform linux/amd64 \
            -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .

      - name: deploy tagged (latest) to Yandex Container Registry
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        env:
          CR_REGISTRY: crpl78lea8jvcc10cnu3
          CR_REPOSITORY: neskuchka
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker buildx build --push \
            --build-arg SKIP_BACKEND_TEST=true --build-arg SKIP_FRONTEND_TEST=true \
            --platform linux/amd64 \
            -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
