name: backend

on:
  push:
    branches:
    tags:
    paths:
      - ".github/workflows/ci-backend.yml"
      - "backend/**"
      - "!backend/bin/**"
      - "!backend/scripts/**"
  
  pull_request:
    types: [opened, reopened]
    paths:
      - ".github/workflows/ci-backend.yml"
      - "backend/**"
      - "!backend/bin/**"
      - "!backend/scripts/**"

jobs:
  test:
    name: Test & Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache-dependency-path: backend

      - name: test and build backend
        run: |
          go test -race -timeout=60s -covermode=atomic -coverprofile=$GITHUB_WORKSPACE/profile.cov_tmp ./...
          cat $GITHUB_WORKSPACE/profile.cov_tmp | grep -v "_mock.go" > $GITHUB_WORKSPACE/profile.cov
          go build -race ./...
        working-directory: backend/app
        env:
          TZ: "Europe/Moscow"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
          working-directory: backend/app

      - name: submit coverage
        uses: coverallsapp/github-action@v2
        with:
          flag-name: backend
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file: $GITHUB_WORKSPACE/profile.cov
          base-path: backend
          parallel: true

